[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "gentodo"
version = "0.0.5"
authors = [
	{name = "Christopher Fore", email = "csfore@posteo.net"},
]
description = "Todo app"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "GPLv3"}

[project.scripts]
gentodo = "gentodo.main:main"

[tool.setuptools]
#package-dir = {"" = "gentodo"}
packages = ["gentodo"]
