#!/usr/bin/env python
# (c) 2023 Christopher Fore
# This code is licensed under the GPLv3 license (see LICENSE for details)

import json
import os
import argparse

STORAGE_DIR = os.path.expanduser("~/.local/share/todo")
TODO_FILE = os.path.join(STORAGE_DIR, "todo.json")

def show_todo():
    with open(TODO_FILE, "r") as todo:
        data = json.load(todo)
    
    print("What to do:")
    print("ID\tItem")
    print("==\t====")
    for key in data:
        print(f"{key}\t{data[key]}")

def add_item():
    if os.path.exists(TODO_FILE) and os.path.getsize(TODO_FILE) > 0:
        with open(TODO_FILE, "r") as todo:
            data = json.load(todo)
            newest_id = int(list(data.keys())[-1])
    else:
        data = {}
        newest_id = 0
    
    data[newest_id + 1] = "{0}".format(args.item)

    with open(TODO_FILE, 'w') as todo:
        json.dump(data, todo, indent=4)

def rm_item():
    if os.path.exists(TODO_FILE) and os.path.getsize(TODO_FILE) > 0:
        with open(TODO_FILE, "r") as todo:
            data = json.load(todo)
            data.pop("{0}".format(args.id))

        with open(TODO_FILE, "w") as todo:
            json.dump(data, todo, indent=4)

def item_count():
    with open(TODO_FILE, "r") as todo:
        data = json.load(todo)
        
    remaining = len(data.keys())
    print(f"Items remaining: {remaining}")

def setup_parser():
    parser = argparse.ArgumentParser()
    parser.set_defaults(func=show_todo)
    parser.add_argument('-v', '--version', action='version', version='0.0.1')
    subparsers = parser.add_subparsers()
    
    add_parser = subparsers.add_parser('add', help="Add an item to your todo list")
    add_parser.add_argument('item', help="Item to add to your todo list")
    add_parser.set_defaults(func=add_item)

    rm_parser = subparsers.add_parser('rm', help="Remove an item from your todo list")
    rm_parser.add_argument('id', help="ID to remove from your todo list")
    rm_parser.set_defaults(func=rm_item)

    count_parser = subparsers.add_parser('count', help="Shows your remaining item count")
    count_parser.set_defaults(func=item_count)

    #parser.add_argument('-a', '--add', type=str)
    #parser.add_argument('-r', '--remove', type=str)
    return parser.parse_args()

def main():
    if not os.path.isdir(STORAGE_DIR):
        print("Storage does not exist")
        os.makedirs(STORAGE_DIR)
    



if __name__ == "__main__":
    args = setup_parser()
    args.func()
    #print(args)
    main()
